services:
  backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./Django_backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./react_frontend
    volumes:
      - frontend:/app/dist
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend/dist
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:
