name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull all latest images 
      run: sudo docker compose pull

    - name: Set up Docker Compose
      run: |
        sudo docker compose down || true
        sudo docker compose up -d
