name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and tag backend image
      run: docker build -t varsubham/backend ./Django_backend

    - name: Build and tag frontend image
      run: docker build -t varsubham/frontend ./react_frontend

    - name: Build and tag nginx image
      run: docker build -t varsubham/nginx ./nginx

    - name: Push backend image to DockerHub
      run: docker push varsubham/backend

    - name: Push frontend image to DockerHub
      run: docker push varsubham/frontend

    - name: Push nginx image to DockerHub
      run: docker push varsubham/nginx
